### ISSUE TITLE
Description: Model confusion - water from dropper and water from faucet are distinct

### ISSUE THREAD

**Issue by terracoda** [phetsims/ph-scale-basics#60]
For description, water is water, just like the visual water is visual water whether or not it comes from the dropper or the faucet.

However, the model seems to see them as different.

Do we fix this in the model, or do we fix this in sim logic?

**Comment by terracoda** [comment]
Will chat with @arouinfar before assigning.

**Comment by pixelzoom** [comment]
The dropper dispenses a solute, one of which is water.  Water from the faucet is a solvent.  The beaker contains a solution, which is a solute dissolved in a solvent.  These are fundamentals of the chemistry model -- the model should not be changed.

This should be fixed in the description logic.  To determine if the solute is water, use the expression `soluteProperty.value === Solutes.WATER`, where the phetioID for `soluteProperty` is `phScaleBasics.macroScreen.model.dropper.soluteProperty`.

**Comment by pixelzoom** [comment]
@terracoda said:
> For description, water is water, just like the visual water is visual water whether or not it comes from the dropper or the faucet.

If you're not differentiating between solute and solvent, then yes "water is water".   But I'm wondering why we are not concerned with the difference between water as a solute and water as a solvent in a chemistry sim about pH.

**Comment by pixelzoom** [comment]
@terracoda said:
> For description, water is water, just like the visual water is visual water whether or not it comes from the dropper or the faucet.

If you're not differentiating between solute and solvent, then yes "water is water".   But I'm wondering why we are not concerned with communicating the difference between water as a solute and water as a solvent in a chemistry sim about pH.

> However, the model seems to see them as different.

Because water has 2 entirely different roles in this sim.  The dropper dispenses a solute, one of which is water.  Water from the faucet is a solvent.  The beaker contains a solution, which is a solute dissolved in a solvent.  These are fundamentals of the chemistry model.

> Do we fix this in the model, or do we fix this in sim logic?

This should be fixed in the description logic.  To determine if the solute is water, use the expression `soluteProperty.value === phet.phScale.Solute.WATER`, where:

```ts
const soluteProperty = context.get( 'phScaleBasics.macroScreen.model.dropper.soluteProperty' );
```

**Comment by terracoda** [comment]
We are not describing things at that level of solute and solvent. I think that is up to the educational context and the grade level of the learners.

Thanks, for description design logic, it means we need to have a special case for water.

We'll do that.
